# Netlify configuration file
# This file tells Netlify how to build and deploy your site.

[build]
  # Command to build your Vite project
  command = "yarn build"
  
  # The directory where the built files are located
  publish = "dist"

[build.environment]
  # Specify the Node.js version to ensure consistency
  NODE_VERSION = "20"
