# Netlify deployment configuration
# This file tells Netlify how to build and deploy your site.

[build]
  # The command to run to build your site
  command = "yarn build"
  
  # The directory that contains the built site
  publish = "dist"

[build.environment]
  # Specify the Node.js version for compatibility
  NODE_VERSION = "20"
